### ISSUE TITLE
[Task]: Basic setup for Design System repository

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/design-system#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Rollup set up
- [ ] NPM packaging set up
- [ ] ESlint configurations
- [ ] Yarn workspace configuration
- [ ] Babel configurations
- [ ] NPM account set up

**Comment by rohitagarwal88** [comment]
Closing this issue. All progress will be tracked at https://github.com/appsmithorg/appsmith/issues/14402
cc @albinAppsmith
